### PR TITLE
Desktop v1.0

### PR DESCRIPTION
**Pull request by DmitriiTsy**
- Created a tablet version of the first page.

### CODE REVIEW

**Comment by DmitriiTsy** [comment]
Screen Shot 2022-06-02 at 15 11 44

Lyft version

**Comment by DmitriiTsy** [comment]
Screen Shot 2022-06-02 at 15 12 19

My version

**Comment by DmitriiTsy** [comment]
@anatoliy8493 

What do you think?

**Comment by ghost** [comment]
... and then merge the latest `main` branch into this PR's branch, ping me here once you do it

**Comment by ghost** [comment]
@DmitriiTsy ⏫

**Comment by ghost** [comment]
the reason why I'm asking this is that we must see changes on a PR that are related only to this PR. Now I see all changes including the mobile version

**Comment by DmitriiTsy** [comment]
@anatoliy8493 Okay, sure

I merged this last commit with the main. Is it okay?

**Pull request merged**
